### ISSUE TITLE
Whitelist style assertions

### ISSUE THREAD

**Issue by mykter** [controlplaneio/netassert#1]
From the README I see that you can specify negative assertions individually using a minus sign:
```
test-frontend: 
      test-microservice: 80
      test-database: -80
```

Is there a means of doing something along the lines of:
```
test-frontend: 
      test-microservice: 80  
```
and having it fail if anything else is accessible?

Typically I'll know which other services a given service should be able to access, but I don't want to have to try and enumerate all the other possible endpoints that it _shouldn't_ be able to access.

**Comment by sublimino** [comment]
Not currently, but there's no reason it couldn't be done - it will just take longer to scan a host. Do you have any suggestion for a prefix? Not sure which of `*`, `~`, or `=` (or other?) to choose:

```
test-frontend: 
      test-microservice: *80 *443
      test-database: ~80 ~443
      test-other: =80 =443
```
